name: vchat
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_lints: ^6.0.0

  # To Change a App Icon 
  flutter_launcher_icons: ^0.14.4

  # For Google Fonts 
  google_fonts: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 
  remove_alpha_ios: true

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/